#!/bin/bash

# Debian + awesome環境自動セットアップスクリプト
# 使用法: 
#   wget -qO- https://github.com/kabochance/Debian_setup/raw/main/setup.sh | bash
# または:
#   wget https://github.com/kabochance/Debian_setup/raw/main/setup.sh && chmod +x setup.sh && ./setup.sh

set -e  # エラー時に停止

echo "=================================================="
echo " Debian + awesome環境自動セットアップ"
echo " https://github.com/kabochance/Debian_setup"
echo "=================================================="

# 実行確認
read -p "セットアップを開始しますか？ (y/N): " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "セットアップを中止しました。"
    exit 1
fi

echo "=== システム更新中... ==="
sudo apt update && sudo apt upgrade -y

echo "=== 基本パッケージインストール中... ==="
sudo apt install -y \
    xorg awesome lightdm \
    alacritty kate ranger firefox-esr \
    network-manager network-manager-gnome \
    pulseaudio pavucontrol \
    dunst xclip parcellite \
    bluez blueman \
    python3 python3-pip python3-venv git \
    build-essential cmake

echo "=== 日本語環境セットアップ中... ==="
sudo apt install -y \
    fonts-noto-cjk fonts-noto-cjk-extra \
    fonts-takao fonts-vlgothic \
    fcitx fcitx-mozc fcitx-config-gtk im-config

echo "=== rangerプレビュー機能セットアップ中... ==="
sudo apt install -y \
    w3m w3m-img highlight atool \
    caca-utils poppler-utils mediainfo \
    libimage-exiftool-perl

echo "=== 環境変数設定中... ==="
if ! grep -q "GTK_IM_MODULE=fcitx" ~/.bashrc; then
    echo 'export GTK_IM_MODULE=fcitx' >> ~/.bashrc
    echo 'export QT_IM_MODULE=fcitx' >> ~/.bashrc
    echo 'export XMODIFIERS=@im=fcitx' >> ~/.bashrc
fi

echo "=== ranger設定中... ==="
if [ ! -f ~/.config/ranger/rc.conf ]; then
    ranger --copy-config=all
fi
sed -i 's/set preview_files false/set preview_files true/' ~/.config/ranger/rc.conf 2>/dev/null || true
sed -i 's/set preview_images false/set preview_images true/' ~/.config/ranger/rc.conf 2>/dev/null || true

echo "=== CQ-editorセットアップ中... ==="
if [ ! -d ~/cq-editor-env ]; then
    python3 -m venv ~/cq-editor-env
    source ~/cq-editor-env/bin/activate
    pip install --upgrade pip
    pip install cadquery
    pip install git+https://github.com/CadQuery/CQ-editor.git
    deactivate
fi

echo "=== CQ-editor起動スクリプト作成中... ==="
cat > ~/start-cq-editor.sh << 'CQ_EOF'
#!/bin/bash
cd ~
source ~/cq-editor-env/bin/activate
cq-editor &
CQ_EOF
chmod +x ~/start-cq-editor.sh

echo "=== awesome設定中... ==="
mkdir -p ~/.config/awesome
if [ ! -f ~/.config/awesome/rc.lua ]; then
    cp /etc/xdg/awesome/rc.lua ~/.config/awesome/
fi

echo "=== 自動起動スクリプト作成中... ==="
cat > ~/.config/awesome/autostart.sh << 'AUTO_EOF'
#!/bin/bash
fcitx &
nm-applet &
pulseaudio --start &
dunst &
parcellite &
blueman-applet &
AUTO_EOF
chmod +x ~/.config/awesome/autostart.sh

echo "=== awesome設定ファイル生成中... ==="
cat > ~/.config/awesome/rc.lua << 'RC_EOF'
-- Generated by Debian_setup
pcall(require, "luarocks.loader")
local gears = require("gears")
local awful = require("awful")
require("awful.autofocus")
local wibox = require("wibox")
local beautiful = require("beautiful")
local naughty = require("naughty")
local hotkeys_popup = require("awful.hotkeys_popup")

-- エラーハンドリング
if awesome.startup_errors then
    naughty.notify({ preset = naughty.config.presets.critical,
                     title = "Oops, there were errors during startup!",
                     text = awesome.startup_errors })
end

-- テーマ
beautiful.init(gears.filesystem.get_themes_dir() .. "default/theme.lua")

-- 変数定義
terminal = "alacritty"
editor = "kate"
modkey = "Mod4"

-- レイアウト
awful.layout.layouts = {
    awful.layout.suit.floating,
    awful.layout.suit.tile,
    awful.layout.suit.max,
    awful.layout.suit.magnifier,
}

-- Wibar
mytextclock = wibox.widget.textclock()

awful.screen.connect_for_each_screen(function(s)
    awful.tag({ "1", "2", "3", "4", "5", "6", "7", "8", "9" }, s, awful.layout.layouts[1])
    
    s.mytaglist = awful.widget.taglist {
        screen  = s,
        filter  = awful.widget.taglist.filter.all,
    }
    
    s.mytasklist = awful.widget.tasklist {
        screen  = s,
        filter  = awful.widget.tasklist.filter.currenttags,
    }
    
    s.mywibox = awful.wibar({ position = "top", screen = s })
    s.mywibox:setup {
        layout = wibox.layout.align.horizontal,
        { layout = wibox.layout.fixed.horizontal, s.mytaglist },
        s.mytasklist,
        { layout = wibox.layout.fixed.horizontal, mytextclock },
    }
end)

-- キーバインド
globalkeys = gears.table.join(
    -- アプリケーション起動
    awful.key({ modkey }, "Return", function () awful.spawn(terminal) end),
    awful.key({ modkey }, "e", function () awful.spawn("kate") end),
    awful.key({ modkey }, "f", function () awful.spawn("alacritty -e ranger") end),
    awful.key({ modkey }, "w", function () awful.spawn("firefox") end),
    awful.key({ modkey }, "q", function () awful.spawn("bash " .. os.getenv("HOME") .. "/start-cq-editor.sh") end),
    
    -- Alt+F4でアプリケーション終了
    awful.key({ "Mod1" }, "F4", function () 
        if client.focus then client.focus:kill() end
    end),
    
    -- 音量調整
    awful.key({}, "XF86AudioRaiseVolume", function()
        awful.spawn("pactl set-sink-volume @DEFAULT_SINK@ +5%")
    end),
    awful.key({}, "XF86AudioLowerVolume", function()
        awful.spawn("pactl set-sink-volume @DEFAULT_SINK@ -5%")
    end),
    awful.key({}, "XF86AudioMute", function()
        awful.spawn("pactl set-sink-mute @DEFAULT_SINK@ toggle")
    end),
    
    -- システム
    awful.key({ modkey, "Control" }, "r", awesome.restart),
    awful.key({ modkey, "Shift"   }, "q", awesome.quit),
    awful.key({ modkey }, "r", function () awful.screen.focused().mypromptbox:run() end)
)

root.keys(globalkeys)

-- クライアント設定
awful.rules.rules = {
    { rule = { },
      properties = { focus = awful.client.focus.filter, raise = true,
                     screen = awful.screen.preferred,
                     placement = awful.placement.no_overlap+awful.placement.no_offscreen }
    },
}

-- 自動起動
awful.spawn.with_shell("~/.config/awesome/autostart.sh")
RC_EOF

echo "=== LightDM有効化中... ==="
sudo systemctl enable lightdm

echo "=================================================="
echo " ✅ セットアップ完了！"
echo "=================================================="
echo ""
echo "次の手順:"
echo "1. 再起動: sudo reboot"
echo "2. ログイン画面でawesomeを選択"
echo "3. 日本語入力: Ctrl+Space"
echo ""
echo "キーバインド:"
echo "- Mod4 + Enter: ターミナル"
echo "- Mod4 + e: エディタ"
echo "- Mod4 + f: ファイラ"
echo "- Mod4 + w: ブラウザ"
echo "- Mod4 + q: CQ-editor"
echo "- Alt + F4: アプリ終了"
echo ""
echo "問題があれば: https://github.com/kabochance/Debian_setup"
echo "=================================================="
