#!/bin/bash

# Debian + awesome environment auto setup script
# Usage: 
#   wget -qO- https://github.com/kabochance/Debian_setup/raw/main/setup.sh | bash
# or:
#   wget https://github.com/kabochance/Debian_setup/raw/main/setup.sh && chmod +x setup.sh && ./setup.sh

set -e  # Stop on error

echo "=================================================="
echo " Debian + awesome Environment Auto Setup"
echo " https://github.com/kabochance/Debian_setup"
echo "=================================================="

# Confirmation
read -p "Start setup? (y/N): " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Setup cancelled."
    exit 1
fi

echo "=== Updating system... ==="
sudo apt update && sudo apt upgrade -y

echo "=== Installing basic packages... ==="
sudo apt install -y \
    xorg awesome lightdm \
    alacritty kate ranger firefox-esr \
    network-manager network-manager-gnome \
    pulseaudio pavucontrol \
    dunst xclip parcellite \
    bluez blueman \
    python3 python3-pip python3-venv git \
    build-essential cmake

echo "=== Setting up Japanese environment... ==="
sudo apt install -y \
    fonts-noto-cjk fonts-noto-cjk-extra \
    fonts-takao fonts-vlgothic \
    fcitx fcitx-mozc fcitx-config-gtk im-config

echo "=== Setting up ranger preview... ==="
sudo apt install -y \
    w3m w3m-img highlight atool \
    caca-utils poppler-utils mediainfo \
    libimage-exiftool-perl

echo "=== Configuring environment variables... ==="
if ! grep -q "GTK_IM_MODULE=fcitx" ~/.bashrc; then
    echo 'export GTK_IM_MODULE=fcitx' >> ~/.bashrc
    echo 'export QT_IM_MODULE=fcitx' >> ~/.bashrc
    echo 'export XMODIFIERS=@im=fcitx' >> ~/.bashrc
fi

echo "=== Configuring ranger... ==="
if [ ! -f ~/.config/ranger/rc.conf ]; then
    ranger --copy-config=all
fi
sed -i 's/set preview_files false/set preview_files true/' ~/.config/ranger/rc.conf 2>/dev/null || true
sed -i 's/set preview_images false/set preview_images true/' ~/.config/ranger/rc.conf 2>/dev/null || true

echo "=== Setting up CQ-editor... ==="
if [ ! -d ~/cq-editor-env ]; then
    python3 -m venv ~/cq-editor-env
    source ~/cq-editor-env/bin/activate
    pip install --upgrade pip
    pip install cadquery
    pip install git+https://github.com/CadQuery/CQ-editor.git
    deactivate
fi

echo "=== Creating CQ-editor launch script... ==="
cat > ~/start-cq-editor.sh << 'CQ_EOF'
#!/bin/bash
cd ~
source ~/cq-editor-env/bin/activate
cq-editor &
CQ_EOF
chmod +x ~/start-cq-editor.sh

echo "=== Configuring awesome... ==="
mkdir -p ~/.config/awesome
if [ ! -f ~/.config/awesome/rc.lua ]; then
    cp /etc/xdg/awesome/rc.lua ~/.config/awesome/
fi

echo "=== Creating autostart script... ==="
cat > ~/.config/awesome/autostart.sh << 'AUTO_EOF'
#!/bin/bash
fcitx &
nm-applet &
pulseaudio --start &
dunst &
parcellite &
blueman-applet &
AUTO_EOF
chmod +x ~/.config/awesome/autostart.sh

echo "=== Generating awesome config file... ==="
cat > ~/.config/awesome/rc.lua << 'RC_EOF'
-- Generated by Debian_setup
pcall(require, "luarocks.loader")
local gears = require("gears")
local awful = require("awful")
require("awful.autofocus")
local wibox = require("wibox")
local beautiful = require("beautiful")
local naughty = require("naughty")
local hotkeys_popup = require("awful.hotkeys_popup")

-- エラーハンドリング
if awesome.startup_errors then
    naughty.notify({ preset = naughty.config.presets.critical,
                     title = "Oops, there were errors during startup!",
                     text = awesome.startup_errors })
end

-- テーマ
beautiful.init(gears.filesystem.get_themes_dir() .. "default/theme.lua")

-- 変数定義
terminal = "alacritty"
editor = "kate"
modkey = "Mod4"

-- レイアウト
awful.layout.layouts = {
    awful.layout.suit.floating,
    awful.layout.suit.tile,
    awful.layout.suit.max,
    awful.layout.suit.magnifier,
}

-- Wibar
mytextclock = wibox.widget.textclock()

awful.screen.connect_for_each_screen(function(s)
    awful.tag({ "1", "2", "3", "4", "5", "6", "7", "8", "9" }, s, awful.layout.layouts[1])
    
    s.mytaglist = awful.widget.taglist {
        screen  = s,
        filter  = awful.widget.taglist.filter.all,
    }
    
    s.mytasklist = awful.widget.tasklist {
        screen  = s,
        filter  = awful.widget.tasklist.filter.currenttags,
    }
    
    s.mywibox = awful.wibar({ position = "top", screen = s })
    s.mywibox:setup {
        layout = wibox.layout.align.horizontal,
        { layout = wibox.layout.fixed.horizontal, s.mytaglist },
        s.mytasklist,
        { layout = wibox.layout.fixed.horizontal, mytextclock },
    }
end)

-- キーバインド
globalkeys = gears.table.join(
    awful.key({ modkey }, "Return", function () awful.spawn(terminal) end),
    awful.key({ modkey }, "e", function () awful.spawn("kate") end),
    awful.key({ modkey }, "f", function () awful.spawn("alacritty -e ranger") end),
    awful.key({ modkey }, "w", function () awful.spawn("firefox") end),

    -- CQ-editor: 仮想環境をアクティベートして直接起動
    awful.key({ modkey }, "q", function ()
        awful.spawn("bash -c 'source /home/hideya/cq-editor-env/bin/activate && cq-editor'")
    end),

    -- Alt+F4でアプリケーション終了
    awful.key({ "Mod1" }, "F4", function () 
        if client.focus then client.focus:kill() end
    end),

    -- 音量調整
    awful.key({}, "XF86AudioRaiseVolume", function()
        awful.spawn("pactl set-sink-volume @DEFAULT_SINK@ +5%")
    end),
    awful.key({}, "XF86AudioLowerVolume", function()
        awful.spawn("pactl set-sink-volume @DEFAULT_SINK@ -5%")
    end),
    awful.key({}, "XF86AudioMute", function()
        awful.spawn("pactl set-sink-mute @DEFAULT_SINK@ toggle")
    end),

    -- システム
    awful.key({ modkey, "Control" }, "r", awesome.restart),
    awful.key({ modkey, "Shift"   }, "q", awesome.quit),
    awful.key({ modkey }, "r", function () awful.screen.focused().mypromptbox:run() end)
)

root.keys(globalkeys)

-- クライアント設定
awful.rules.rules = {
    { rule = { },
      properties = { focus = awful.client.focus.filter, raise = true,
                     screen = awful.screen.preferred,
                     placement = awful.placement.no_overlap+awful.placement.no_offscreen }
    },
}

-- 自動起動
awful.spawn.with_shell("~/.config/awesome/autostart.sh")
RC_EOF


echo "=== Enabling LightDM... ==="
sudo systemctl enable lightdm

echo "=================================================="
echo " ✅ Setup Complete!"
echo "=================================================="
echo ""
echo "=== Setting system locale to Japanese... ==="
sudo apt install -y locales
sudo sed -i 's/# ja_JP.UTF-8 UTF-8/ja_JP.UTF-8 UTF-8/' /etc/locale.gen
sudo locale-gen
sudo update-locale LANG=ja_JP.UTF-8

echo ""
echo "Next steps:"
echo "1. Reboot: sudo reboot"
echo "2. At login screen, select 'awesome' session"
echo "3. After login, do the following to enable Japanese input:"
echo "   - Run: im-config and choose 'fcitx'!!!"
echo "   - Run: fcitx-configtool and add 'Mozc (Japanese)'!!!"
echo ""
echo "   You can then switch input method with Ctrl+Space"
echo ""
echo "System locale has been changed to Japanese (ja_JP.UTF-8)"
echo "If it does not take effect, reboot once"
echo ""
echo "Key bindings:"
echo "- Mod4 + Enter: Terminal"
echo "- Mod4 + e: Editor"
echo "- Mod4 + f: File manager"
echo "- Mod4 + w: Web browser"
echo "- Mod4 + q: CQ-editor"
echo "- Alt + F4: Close application"
echo ""
echo "Issues: https://github.com/kabochance/Debian_setup"
echo "=================================================="
